// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf6bfwLKk-coZ8ETOIUqTfbQna1AngaVE',
    appId: '1:696895611407:android:a6f1f99745cb46650fb97a',
    messagingSenderId: '696895611407',
    projectId: 'tablestat-c3ad8',
    databaseURL:
        'https://tablestat-c3ad8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tablestat-c3ad8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVIMEyNn7wlVHogIXxy7EMLRbr0iqdZ0',
    appId: '1:696895611407:ios:492c2965b0b5315f0fb97a',
    messagingSenderId: '696895611407',
    projectId: 'tablestat-c3ad8',
    databaseURL:
        'https://tablestat-c3ad8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tablestat-c3ad8.appspot.com',
    iosBundleId: 'com.example.tableStat',
  );
}
